# initial params
SOCKET_CONFIGURATION:
  robot_ip: "192.168.31.10"
  port_number: 30003

HOME_JOINTS:
  -
    - -72.94
    - -80.84
    - -130.1
  -
    - -51.87
    - 111.72
    - -161.44

HOME_POSE:
  -
    - 0.03
    - -0.54
    - 0.4
  -
    - 3.14
    - -0.4
    - 0
PICK_Z: 0.
PLACE_Z: 0.08

