site_name: DeepClaw
nav:
    - Home:
      - Overview: overview.md
      - Installation: install.md
    - Manual:
      - DeepClaw Pipeline: pipeline.md
      - Robot Library: robot.md
      - Module Pool: module.md
      - Task Family: task.md
      - Common Dataset: data.md
      - Sim-2-Real: sim2real.md
    - API:
      - deepclaw: code-api.md
    - Notes:
      - Licence: licence.md
      - Release Note: release.md
      - For Developers: devnote.md
      # - For Users (TODO): usenote.md
theme: readthedocs


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
